const API_BASE = "http://127.0.0.1:8000/api";
const state = { auth: { token: sessionStorage.getItem("ua_token") || "", username: sessionStorage.getItem("ua_username") || "", roles: JSON.parse(sessionStorage.getItem("ua_roles") || "[]"), user: null }, programmes: [], students: [], courses: [], courseInstances: [], enrollments: [], grades: [], protocols: [] };
const authScreen = document.getElementById("auth-screen");
const appShell = document.getElementById("app-shell");
const loginForm = document.getElementById("login-form");
const authMessageBox = document.getElementById("auth-message");
const loginSubmitBtn = document.getElementById("login-submit");
const fillDemoLoginBtn = document.getElementById("fill-demo-login");
const logoutBtn = document.getElementById("logout-btn");
const currentUsernameEl = document.getElementById("current-username");
const currentUserRolesEl = document.getElementById("current-user-roles");
const views = document.querySelectorAll(".view");
const navButtons = document.querySelectorAll(".nav-btn");
const viewTitle = document.getElementById("view-title");
const messageBox = document.getElementById("message");
const viewTitles = { dashboard: "Табло", programmes: "Програми", students: "Студенти", courses: "Дисциплини", "course-instances": "Провеждания", enrollments: "Записвания", grades: "Оценки", protocols: "Протоколи", reports: "Справки" };
function setSessionAuth(token, username, roles) { state.auth.token = token || ""; state.auth.username = username || ""; state.auth.roles = Array.isArray(roles) ? roles : []; if (state.auth.token) { sessionStorage.setItem("ua_token", state.auth.token); sessionStorage.setItem("ua_username", state.auth.username || ""); sessionStorage.setItem("ua_roles", JSON.stringify(state.auth.roles)); } else { sessionStorage.removeItem("ua_token"); sessionStorage.removeItem("ua_username"); sessionStorage.removeItem("ua_roles"); } }
function showMessage(text, type = "success") { messageBox.textContent = text; messageBox.className = `message ${type}`; clearTimeout(showMessage._timer); showMessage._timer = setTimeout(() => { messageBox.className = "message"; messageBox.textContent = ""; }, 3500); }
function showAuthMessage(text, type = "error") { authMessageBox.textContent = text; authMessageBox.className = `message ${type}`; clearTimeout(showAuthMessage._timer); showAuthMessage._timer = setTimeout(() => { authMessageBox.className = "message"; authMessageBox.textContent = ""; }, 3500); }
function setAuthLoading(isLoading) { loginSubmitBtn.disabled = isLoading; loginSubmitBtn.textContent = isLoading ? "Влизане..." : "Вход в системата"; }
function updateCurrentUserUI() { const username = state.auth.user?.username || state.auth.username || "—"; const roles = state.auth.user?.roles?.map((role) => role.name).join(", ") || state.auth.roles.join(", ") || "—"; currentUsernameEl.textContent = username; currentUserRolesEl.textContent = roles; }
function setAuthenticatedUI(isAuthenticated) { authScreen.classList.toggle("hidden", isAuthenticated); appShell.classList.toggle("hidden", !isAuthenticated); }
function switchView(viewId) { views.forEach((view) => view.classList.remove("active")); navButtons.forEach((btn) => btn.classList.remove("active")); const targetView = document.getElementById(viewId); const targetBtn = document.querySelector(`.nav-btn[data-view="${viewId}"]`); if (targetView) targetView.classList.add("active"); if (targetBtn) targetBtn.classList.add("active"); viewTitle.textContent = viewTitles[viewId] || "University Admin"; }
navButtons.forEach((btn) => btn.addEventListener("click", () => switchView(btn.dataset.view)));
document.querySelectorAll("[data-open-view]").forEach((btn) => btn.addEventListener("click", () => switchView(btn.dataset.openView)));
async function request(endpoint, options = {}) { const headers = { ...(options.headers || {}) }; if (state.auth.token) headers.Authorization = `Bearer ${state.auth.token}`; if (!(options.body instanceof FormData) && !headers["Content-Type"]) headers["Content-Type"] = "application/json"; const response = await fetch(`${API_BASE}${endpoint}`, { ...options, headers }); const contentType = response.headers.get("content-type") || ""; const payload = contentType.includes("application/json") ? await response.json().catch(() => null) : await response.text().catch(() => ""); if (response.status === 401) { logout(false); throw new Error("Сесията е изтекла или токенът е невалиден. Влез отново."); } if (!response.ok) { const detail = typeof payload === "object" && payload?.detail ? payload.detail : typeof payload === "string" && payload ? payload : "Възникна грешка при заявката."; throw new Error(detail); } return payload; }
async function login(username, password) { const body = new URLSearchParams(); body.append("username", username); body.append("password", password); const response = await fetch(`${API_BASE}/auth/login`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: body.toString() }); const contentType = response.headers.get("content-type") || ""; const payload = contentType.includes("application/json") ? await response.json().catch(() => null) : await response.text().catch(() => ""); if (!response.ok) { const detail = typeof payload === "object" && payload?.detail ? payload.detail : typeof payload === "string" && payload ? payload : "Неуспешен вход."; throw new Error(detail); } setSessionAuth(payload.access_token, payload.username, payload.roles); return payload; }
async function loadCurrentUser() { const user = await request("/auth/me"); state.auth.user = user; updateCurrentUserUI(); return user; }
function logout(showInfo = true) { setSessionAuth("", "", []); state.auth.user = null; updateCurrentUserUI(); setAuthenticatedUI(false); loginForm.reset(); switchView("dashboard"); if (showInfo) showAuthMessage("Излязохте успешно от системата.", "success"); }
function safeValue(value) { return value ?? ""; }
function numericOrNull(value) { if (value === "" || value === null || value === undefined) return null; const parsed = Number(value); return Number.isNaN(parsed) ? null : parsed; }
function stringOrNull(value) { if (value === null || value === undefined) return null; const trimmed = String(value).trim(); return trimmed === "" ? null : trimmed; }
function boolBadge(value) { return value ? "Да" : "Не"; }
function createActionButtons({ disableDelete = false } = {}) { return `<div class="actions-cell"><button class="action-btn edit" data-action="edit">Редакция</button><button class="action-btn delete" data-action="delete" ${disableDelete ? "disabled" : ""}>Изтрий</button></div>`; }
function bindRowActions(tbody, items, handlers) { Array.from(tbody.querySelectorAll("tr")).forEach((tr, index) => { const item = items[index]; const editBtn = tr.querySelector('[data-action="edit"]'); const deleteBtn = tr.querySelector('[data-action="delete"]'); if (editBtn && handlers.onEdit) editBtn.addEventListener("click", () => handlers.onEdit(item)); if (deleteBtn && handlers.onDelete && !deleteBtn.disabled) deleteBtn.addEventListener("click", () => handlers.onDelete(item)); }); }
function resetForm(formId) { document.getElementById(formId).reset(); }
function updateDashboardStats() { document.getElementById("stat-students").textContent = state.students.length; document.getElementById("stat-courses").textContent = state.courses.length; document.getElementById("stat-grades").textContent = state.grades.length; document.getElementById("stat-protocols").textContent = state.protocols.length; }
function fillProgrammeForm(item) { document.getElementById("programme-id").value = item.id ?? ""; document.getElementById("programme-code").value = safeValue(item.code); document.getElementById("programme-name").value = safeValue(item.name); document.getElementById("programme-degree").value = safeValue(item.degree); document.getElementById("programme-field").value = safeValue(item.field); switchView("programmes"); }
function clearProgrammeForm() { resetForm("programme-form"); document.getElementById("programme-id").value = ""; }
async function loadProgrammes() { const data = await request("/programmes"); state.programmes = Array.isArray(data) ? data : []; const tbody = document.getElementById("programmes-table"); tbody.innerHTML = ""; state.programmes.forEach((programme) => { const tr = document.createElement("tr"); tr.innerHTML = `<td>${programme.id}</td><td>${safeValue(programme.code)}</td><td>${safeValue(programme.name)}</td><td>${safeValue(programme.degree)}</td><td>${safeValue(programme.field)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.programmes, { onEdit: fillProgrammeForm, onDelete: async (item) => { if (!confirm(`Изтриване на програма ${item.code}?`)) return; await request(`/programmes/${item.id}`, { method: "DELETE" }); showMessage("Програмата е изтрита успешно."); await loadProgrammes(); } }); }
document.getElementById("programme-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("programme-id").value; const payload = { code: document.getElementById("programme-code").value.trim(), name: document.getElementById("programme-name").value.trim(), degree: stringOrNull(document.getElementById("programme-degree").value), field: stringOrNull(document.getElementById("programme-field").value) }; try { await request(id ? `/programmes/${id}` : "/programmes", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Програмата е обновена успешно." : "Програмата е създадена успешно."); clearProgrammeForm(); await loadProgrammes(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("programme-cancel").addEventListener("click", clearProgrammeForm);
document.getElementById("refresh-programmes").addEventListener("click", async () => { try { await loadProgrammes(); showMessage("Програмите са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function fillStudentForm(item) { document.getElementById("student-id").value = item.id ?? ""; document.getElementById("student-faculty-number").value = safeValue(item.faculty_number); document.getElementById("student-first-name").value = safeValue(item.first_name); document.getElementById("student-last-name").value = safeValue(item.last_name); document.getElementById("student-email").value = safeValue(item.email); document.getElementById("student-admission-year").value = safeValue(item.admission_year); document.getElementById("student-study-form").value = safeValue(item.study_form); document.getElementById("student-programme-id").value = safeValue(item.programme_code); switchView("students"); }
function clearStudentForm() { resetForm("student-form"); document.getElementById("student-id").value = ""; }
async function loadStudents() { const data = await request("/students"); state.students = Array.isArray(data) ? data : []; const tbody = document.getElementById("students-table"); tbody.innerHTML = ""; state.students.forEach((student) => { const fullName = `${safeValue(student.first_name)} ${safeValue(student.last_name)}`.trim(); const tr = document.createElement("tr"); tr.innerHTML = `<td>${student.id}</td><td>${safeValue(student.faculty_number)}</td><td>${fullName}</td><td>${safeValue(student.email)}</td><td>${safeValue(student.admission_year)}</td><td>${safeValue(student.study_form)}</td><td>${safeValue(student.programme_code)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.students, { onEdit: fillStudentForm, onDelete: async (item) => { if (!confirm(`Изтриване на студент ${item.faculty_number}?`)) return; await request(`/students/${item.id}`, { method: "DELETE" }); showMessage("Студентът е изтрит успешно."); await loadStudents(); updateDashboardStats(); } }); }
document.getElementById("student-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("student-id").value; const payload = { faculty_number: document.getElementById("student-faculty-number").value.trim(), first_name: document.getElementById("student-first-name").value.trim(), last_name: document.getElementById("student-last-name").value.trim(), email: stringOrNull(document.getElementById("student-email").value), admission_year: numericOrNull(document.getElementById("student-admission-year").value), study_form: stringOrNull(document.getElementById("student-study-form").value), programme_code: stringOrNull(document.getElementById("student-programme-id").value) }; try { await request(id ? `/students/${id}` : "/students", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Студентът е обновен успешно." : "Студентът е създаден успешно."); clearStudentForm(); await loadStudents(); updateDashboardStats(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("student-cancel").addEventListener("click", clearStudentForm);
document.getElementById("refresh-students").addEventListener("click", async () => { try { await loadStudents(); updateDashboardStats(); showMessage("Студентите са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function fillCourseForm(item) { document.getElementById("course-id").value = item.id ?? ""; document.getElementById("course-code").value = safeValue(item.code); document.getElementById("course-name").value = safeValue(item.name); document.getElementById("course-semester").value = safeValue(item.semester); document.getElementById("course-mandatory-type").value = safeValue(item.mandatory_type); document.getElementById("course-credits").value = safeValue(item.credits); document.getElementById("course-hours-lectures").value = safeValue(item.hours_lectures); document.getElementById("course-hours-exercises").value = safeValue(item.hours_exercises); document.getElementById("course-programme-id").value = safeValue(item.programme_code); switchView("courses"); }
function clearCourseForm() { resetForm("course-form"); document.getElementById("course-id").value = ""; }
async function loadCourses() { const data = await request("/courses"); state.courses = Array.isArray(data) ? data : []; const tbody = document.getElementById("courses-table"); tbody.innerHTML = ""; state.courses.forEach((course) => { const tr = document.createElement("tr"); tr.innerHTML = `<td>${course.id}</td><td>${safeValue(course.code)}</td><td>${safeValue(course.name)}</td><td>${safeValue(course.semester)}</td><td>${safeValue(course.credits)}</td><td>${safeValue(course.mandatory_type)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.courses, { onEdit: fillCourseForm, onDelete: async (item) => { if (!confirm(`Изтриване на дисциплина ${item.code}?`)) return; await request(`/courses/${item.id}`, { method: "DELETE" }); showMessage("Дисциплината е изтрита успешно."); await loadCourses(); updateDashboardStats(); } }); }
document.getElementById("course-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("course-id").value; const payload = { code: document.getElementById("course-code").value.trim(), name: document.getElementById("course-name").value.trim(), semester: numericOrNull(document.getElementById("course-semester").value), mandatory_type: stringOrNull(document.getElementById("course-mandatory-type").value), credits: numericOrNull(document.getElementById("course-credits").value), hours_lectures: numericOrNull(document.getElementById("course-hours-lectures").value), hours_exercises: numericOrNull(document.getElementById("course-hours-exercises").value), programme_code: stringOrNull(document.getElementById("course-programme-id").value) }; try { await request(id ? `/courses/${id}` : "/courses", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Дисциплината е обновена успешно." : "Дисциплината е създадена успешно."); clearCourseForm(); await loadCourses(); updateDashboardStats(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("course-cancel").addEventListener("click", clearCourseForm);
document.getElementById("refresh-courses").addEventListener("click", async () => { try { await loadCourses(); updateDashboardStats(); showMessage("Дисциплините са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function fillCourseInstanceForm(item) { document.getElementById("course-instance-id").value = item.id ?? ""; document.getElementById("course-instance-academic-year").value = safeValue(item.academic_year); document.getElementById("course-instance-term").value = safeValue(item.term); document.getElementById("course-instance-group").value = safeValue(item.group); document.getElementById("course-instance-course-id").value = safeValue(item.course_id); switchView("course-instances"); }
function clearCourseInstanceForm() { resetForm("course-instance-form"); document.getElementById("course-instance-id").value = ""; }
async function loadCourseInstances() { const data = await request("/course-instances"); state.courseInstances = Array.isArray(data) ? data : []; const tbody = document.getElementById("course-instances-table"); tbody.innerHTML = ""; state.courseInstances.forEach((item) => { const courseLabel = [item.course_code, item.course_name].filter(Boolean).join(" • "); const tr = document.createElement("tr"); tr.innerHTML = `<td>${item.id}</td><td>${safeValue(item.academic_year)}</td><td>${safeValue(item.term)}</td><td>${safeValue(item.group)}</td><td>${safeValue(item.course_id)}</td><td>${safeValue(courseLabel)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.courseInstances, { onEdit: fillCourseInstanceForm, onDelete: async (item) => { if (!confirm(`Изтриване на провеждане ${item.id}?`)) return; await request(`/course-instances/${item.id}`, { method: "DELETE" }); showMessage("Провеждането е изтрито успешно."); await loadCourseInstances(); } }); }
document.getElementById("course-instance-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("course-instance-id").value; const payload = { academic_year: document.getElementById("course-instance-academic-year").value.trim(), term: stringOrNull(document.getElementById("course-instance-term").value), group: stringOrNull(document.getElementById("course-instance-group").value), course_id: numericOrNull(document.getElementById("course-instance-course-id").value) }; try { await request(id ? `/course-instances/${id}` : "/course-instances", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Провеждането е обновено успешно." : "Провеждането е създадено успешно."); clearCourseInstanceForm(); await loadCourseInstances(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("course-instance-cancel").addEventListener("click", clearCourseInstanceForm);
document.getElementById("refresh-course-instances").addEventListener("click", async () => { try { await loadCourseInstances(); showMessage("Провежданията са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function fillEnrollmentForm(item) { document.getElementById("enrollment-id").value = item.id ?? ""; document.getElementById("enrollment-student-id").value = safeValue(item.student_id); document.getElementById("enrollment-course-instance-id").value = safeValue(item.course_instance_id); document.getElementById("enrollment-status").value = safeValue(item.status); switchView("enrollments"); }
function clearEnrollmentForm() { resetForm("enrollment-form"); document.getElementById("enrollment-id").value = ""; }
async function loadEnrollments() { const data = await request("/enrollments"); state.enrollments = Array.isArray(data) ? data : []; const tbody = document.getElementById("enrollments-table"); tbody.innerHTML = ""; state.enrollments.forEach((item) => { const courseLabel = [item.course_code, item.course_name].filter(Boolean).join(" • "); const tr = document.createElement("tr"); tr.innerHTML = `<td>${item.id}</td><td>${safeValue(item.student_id)}</td><td>${safeValue(item.course_instance_id)}</td><td>${safeValue(item.status)}</td><td>${safeValue(item.academic_year)}</td><td>${safeValue(courseLabel)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.enrollments, { onEdit: fillEnrollmentForm, onDelete: async (item) => { if (!confirm(`Изтриване на записване ${item.id}?`)) return; await request(`/enrollments/${item.id}`, { method: "DELETE" }); showMessage("Записването е изтрито успешно."); await loadEnrollments(); } }); }
document.getElementById("enrollment-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("enrollment-id").value; const payload = { student_id: numericOrNull(document.getElementById("enrollment-student-id").value), course_instance_id: numericOrNull(document.getElementById("enrollment-course-instance-id").value), status: stringOrNull(document.getElementById("enrollment-status").value) }; try { await request(id ? `/enrollments/${id}` : "/enrollments", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Записването е обновено успешно." : "Записването е създадено успешно."); clearEnrollmentForm(); await loadEnrollments(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("enrollment-cancel").addEventListener("click", clearEnrollmentForm);
document.getElementById("refresh-enrollments").addEventListener("click", async () => { try { await loadEnrollments(); showMessage("Записванията са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function fillGradeForm(item) { document.getElementById("grade-id").value = item.id ?? ""; document.getElementById("grade-protocol-entry-id").value = safeValue(item.protocol_entry_id); document.getElementById("grade-enrollment-id").value = safeValue(item.enrollment_id); document.getElementById("grade-academic-year").value = safeValue(item.academic_year); document.getElementById("grade-exam-date").value = safeValue(item.exam_date); document.getElementById("grade-grade-numeric").value = safeValue(item.grade_numeric); document.getElementById("grade-grade-text-bg").value = safeValue(item.grade_text_bg); document.getElementById("grade-grade-ects").value = safeValue(item.grade_ects); document.getElementById("grade-is-transferred").checked = Boolean(item.is_transferred); switchView("grades"); }
function clearGradeForm() { resetForm("grade-form"); document.getElementById("grade-id").value = ""; document.getElementById("grade-is-transferred").checked = false; }
async function loadGrades() { const data = await request("/grades"); state.grades = Array.isArray(data) ? data : []; const tbody = document.getElementById("grades-table"); tbody.innerHTML = ""; state.grades.forEach((item) => { const tr = document.createElement("tr"); tr.innerHTML = `<td>${item.id}</td><td>${safeValue(item.enrollment_id)}</td><td>${safeValue(item.academic_year)}</td><td>${safeValue(item.grade_numeric)}</td><td>${safeValue(item.grade_ects)}</td><td>${safeValue(item.exam_date)}</td><td>${boolBadge(item.is_transferred)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.grades, { onEdit: fillGradeForm, onDelete: async (item) => { if (!confirm(`Изтриване на оценка ${item.id}?`)) return; await request(`/grades/${item.id}`, { method: "DELETE" }); showMessage("Оценката е изтрита успешно."); await loadGrades(); updateDashboardStats(); } }); }
document.getElementById("grade-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("grade-id").value; const payload = { protocol_entry_id: numericOrNull(document.getElementById("grade-protocol-entry-id").value), enrollment_id: numericOrNull(document.getElementById("grade-enrollment-id").value), academic_year: document.getElementById("grade-academic-year").value.trim(), exam_date: stringOrNull(document.getElementById("grade-exam-date").value), grade_numeric: numericOrNull(document.getElementById("grade-grade-numeric").value), grade_text_bg: stringOrNull(document.getElementById("grade-grade-text-bg").value), grade_ects: stringOrNull(document.getElementById("grade-grade-ects").value), is_transferred: document.getElementById("grade-is-transferred").checked }; try { await request(id ? `/grades/${id}` : "/grades", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Оценката е обновена успешно." : "Оценката е създадена успешно."); clearGradeForm(); await loadGrades(); updateDashboardStats(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("grade-cancel").addEventListener("click", clearGradeForm);
document.getElementById("refresh-grades").addEventListener("click", async () => { try { await loadGrades(); updateDashboardStats(); showMessage("Оценките са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function fillProtocolForm(item) { document.getElementById("protocol-id").value = item.id ?? ""; document.getElementById("protocol-number").value = safeValue(item.protocol_number); document.getElementById("protocol-type").value = safeValue(item.protocol_type); document.getElementById("protocol-date").value = safeValue(item.protocol_date); document.getElementById("protocol-academic-year").value = safeValue(item.academic_year); document.getElementById("protocol-course-instance-id").value = safeValue(item.course_instance_id); document.getElementById("protocol-teacher-id").value = safeValue(item.teacher_id); document.getElementById("protocol-notes").value = safeValue(item.notes); switchView("protocols"); }
function clearProtocolForm() { resetForm("protocol-form"); document.getElementById("protocol-id").value = ""; }
async function loadProtocols() { const data = await request("/protocols"); state.protocols = Array.isArray(data) ? data : []; const tbody = document.getElementById("protocols-table"); tbody.innerHTML = ""; state.protocols.forEach((item) => { const tr = document.createElement("tr"); tr.innerHTML = `<td>${item.id}</td><td>${safeValue(item.protocol_number)}</td><td>${safeValue(item.protocol_type)}</td><td>${safeValue(item.protocol_date)}</td><td>${safeValue(item.academic_year)}</td><td>${safeValue(item.course_instance_id)}</td><td>${safeValue(item.teacher_name)}</td><td>${createActionButtons()}</td>`; tbody.appendChild(tr); }); bindRowActions(tbody, state.protocols, { onEdit: fillProtocolForm, onDelete: async (item) => { if (!confirm(`Изтриване на протокол ${item.protocol_number}?`)) return; await request(`/protocols/${item.id}`, { method: "DELETE" }); showMessage("Протоколът е изтрит успешно."); await loadProtocols(); updateDashboardStats(); } }); }
document.getElementById("protocol-form").addEventListener("submit", async (e) => { e.preventDefault(); const id = document.getElementById("protocol-id").value; const payload = { protocol_number: document.getElementById("protocol-number").value.trim(), protocol_type: document.getElementById("protocol-type").value.trim(), protocol_date: document.getElementById("protocol-date").value, academic_year: document.getElementById("protocol-academic-year").value.trim(), course_instance_id: numericOrNull(document.getElementById("protocol-course-instance-id").value), teacher_id: numericOrNull(document.getElementById("protocol-teacher-id").value), notes: stringOrNull(document.getElementById("protocol-notes").value) }; try { await request(id ? `/protocols/${id}` : "/protocols", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }); showMessage(id ? "Протоколът е обновен успешно." : "Протоколът е създаден успешно."); clearProtocolForm(); await loadProtocols(); updateDashboardStats(); } catch (error) { showMessage(error.message, "error"); } });
document.getElementById("protocol-cancel").addEventListener("click", clearProtocolForm);
document.getElementById("refresh-protocols").addEventListener("click", async () => { try { await loadProtocols(); updateDashboardStats(); showMessage("Протоколите са обновени."); } catch (error) { showMessage(error.message, "error"); } });
function renderStudentProfileCard(data) { const container = document.getElementById("student-profile-card"); const student = data.student; container.innerHTML = `<h4>${safeValue(student.first_name)} ${safeValue(student.last_name)}</h4><p><strong>Факултетен номер:</strong> ${safeValue(student.faculty_number)}</p><p><strong>Email:</strong> ${safeValue(student.email)}</p><p><strong>Година на прием:</strong> ${safeValue(student.admission_year)}</p><p><strong>Форма на обучение:</strong> ${safeValue(student.study_form)}</p><p><strong>Специалност:</strong> ${student.programme ? `${safeValue(student.programme.code)} ${safeValue(student.programme.name)}` : ""}</p>`; container.classList.remove("hidden"); }
function renderAcademicRecords(records = []) { const tbody = document.getElementById("student-profile-table"); tbody.innerHTML = ""; records.forEach((record) => { const allGradesText = (record.all_grades || []).map((g) => `${g.grade_numeric ?? "-"} (${g.protocol_type ?? "без протокол"})`).join(", "); const tr = document.createElement("tr"); tr.innerHTML = `<td>${safeValue(record.course_name)}</td><td>${safeValue(record.course_code)}</td><td>${safeValue(record.academic_year)}</td><td>${safeValue(record.term)}</td><td>${safeValue(record.group)}</td><td>${safeValue(record.best_grade)}</td><td>${safeValue(record.protocol_number)}</td><td>${safeValue(allGradesText)}</td>`; tbody.appendChild(tr); }); }
document.getElementById("student-profile-form").addEventListener("submit", async (e) => { e.preventDefault(); const studentId = document.getElementById("student-profile-id").value; if (!studentId) return showMessage("Моля, въведи Student ID.", "error"); try { const data = await request(`/reports/student-profile/${studentId}`); renderStudentProfileCard(data); renderAcademicRecords(data.academic_records || []); showMessage("Справката е заредена успешно."); } catch (error) { showMessage(error.message, "error"); } });
loginForm.addEventListener("submit", async (e) => { e.preventDefault(); const username = document.getElementById("login-username").value.trim(); const password = document.getElementById("login-password").value; if (!username || !password) return showAuthMessage("Моля, попълни потребителско име и парола.", "error"); try { setAuthLoading(true); await login(username, password); await loadCurrentUser(); setAuthenticatedUI(true); showMessage("Успешен вход в системата."); showAuthMessage("Входът е успешен.", "success"); await initAppData(); } catch (error) { showAuthMessage(error.message, "error"); } finally { setAuthLoading(false); } });
fillDemoLoginBtn.addEventListener("click", () => { document.getElementById("login-username").value = "admin"; document.getElementById("login-password").value = "admin123"; });
logoutBtn.addEventListener("click", () => logout(true));
async function initAppData() { const results = await Promise.allSettled([loadProgrammes(), loadStudents(), loadCourses(), loadCourseInstances(), loadEnrollments(), loadGrades(), loadProtocols()]); const rejected = results.find((result) => result.status === "rejected"); updateDashboardStats(); if (rejected) showMessage(rejected.reason?.message || "Част от данните не бяха заредени.", "error"); }
async function bootstrap() { if (!state.auth.token) return setAuthenticatedUI(false); try { await loadCurrentUser(); setAuthenticatedUI(true); await initAppData(); } catch (error) { logout(false); showAuthMessage(error.message, "error"); } }
bootstrap();
